# Generated by Django 5.2.11 on 2026-02-17 20:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cases', '0004_scenereport_scenewitness'),
        ('evidence', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DetectiveBoard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('case', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='detective_board', to='cases.case')),
            ],
        ),
        migrations.CreateModel(
            name='BoardItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('evidence', 'Evidence'), ('note', 'Note')], max_length=16)),
                ('note_text', models.TextField(blank=True, default='')),
                ('position_x', models.FloatField(default=0.0)),
                ('position_y', models.FloatField(default=0.0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('evidence', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='board_items', to='evidence.evidence')),
                ('board', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='investigations.detectiveboard')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='BoardConnection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('from_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='connections_from', to='investigations.boarditem')),
                ('to_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='connections_to', to='investigations.boarditem')),
                ('board', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='connections', to='investigations.detectiveboard')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.AddConstraint(
            model_name='boarditem',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('evidence__isnull', False), ('note_text', '')), models.Q(('evidence__isnull', True), models.Q(('note_text', ''), _negated=True)), _connector='OR'), name='boarditem_evidence_xor_note'),
        ),
        migrations.AddConstraint(
            model_name='boardconnection',
            constraint=models.CheckConstraint(condition=models.Q(('from_item', models.F('to_item')), _negated=True), name='boardconnection_not_self'),
        ),
        migrations.AddConstraint(
            model_name='boardconnection',
            constraint=models.UniqueConstraint(fields=('board', 'from_item', 'to_item'), name='uniq_boardconnection_board_from_to'),
        ),
    ]
