# Generated by Django 5.x on 2026-02-18

import django.db.models.deletion
from django.conf import settings
from django.core.validators import MaxValueValidator, MinValueValidator
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("investigations", "0003_casesuspect"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Interrogation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "detective_score",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        null=True,
                        validators=[MinValueValidator(1), MaxValueValidator(10)],
                    ),
                ),
                (
                    "detective_submitted_at",
                    models.DateTimeField(blank=True, null=True),
                ),
                (
                    "sergeant_score",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        null=True,
                        validators=[MinValueValidator(1), MaxValueValidator(10)],
                    ),
                ),
                (
                    "sergeant_submitted_at",
                    models.DateTimeField(blank=True, null=True),
                ),
                (
                    "captain_final_decision",
                    models.BooleanField(blank=True, null=True),
                ),
                (
                    "captain_reasoning",
                    models.TextField(blank=True, default=""),
                ),
                (
                    "captain_decided_at",
                    models.DateTimeField(blank=True, null=True),
                ),
                (
                    "chief_decision",
                    models.BooleanField(blank=True, null=True),
                ),
                (
                    "chief_message",
                    models.TextField(blank=True, default=""),
                ),
                (
                    "chief_reviewed_at",
                    models.DateTimeField(blank=True, null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "captain_decided_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="interrogations_captain_decided",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "chief_reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="interrogations_chief_reviewed",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "detective_submitted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="interrogations_detective_submitted",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "sergeant_submitted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="interrogations_sergeant_submitted",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "suspect",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="interrogation",
                        to="investigations.casesuspect",
                    ),
                ),
            ],
            options={
                "ordering": ["-updated_at"],
                "permissions": [
                    ("submit_detective_interrogation", "Can submit detective interrogation score"),
                    ("submit_sergeant_interrogation", "Can submit sergeant interrogation score"),
                    ("submit_captain_interrogation_decision", "Can submit captain interrogation decision"),
                    ("review_critical_interrogation", "Can review critical case interrogation (chief)"),
                ],
            },
        ),
    ]

