# Generated by Django 5.x on 2026-02-18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cases", "0005_trial"),
        ("investigations", "0004_interrogation"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="casesuspect",
            name="photo",
            field=models.ImageField(blank=True, null=True, upload_to="suspects/"),
        ),
        migrations.CreateModel(
            name="Tip",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("details", models.TextField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("submitted", "Submitted"),
                            ("officer_rejected", "Officer Rejected"),
                            ("forwarded_to_detective", "Forwarded to Detective"),
                            ("detective_rejected", "Detective Rejected"),
                            ("approved", "Approved"),
                        ],
                        default="submitted",
                        max_length=32,
                    ),
                ),
                ("officer_message", models.TextField(blank=True, default="")),
                ("officer_reviewed_at", models.DateTimeField(blank=True, null=True)),
                ("detective_message", models.TextField(blank=True, default="")),
                ("detective_reviewed_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "case",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tips",
                        to="cases.case",
                    ),
                ),
                (
                    "detective_reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="tips_detective_reviewed",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "officer_reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="tips_officer_reviewed",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "suspect",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tips",
                        to="investigations.casesuspect",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tips",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "permissions": [
                    ("officer_review_tip", "Can perform officer review on tips"),
                    ("detective_review_tip", "Can perform detective review on tips"),
                    ("reward_lookup", "Can lookup rewards by code and national id"),
                ],
            },
        ),
        migrations.CreateModel(
            name="Reward",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("reward_code", models.CharField(max_length=64, unique=True)),
                ("reward_amount", models.BigIntegerField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "tip",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reward",
                        to="investigations.tip",
                    ),
                ),
            ],
        ),
    ]

