# Generated by Django 5.2.11 on 2026-02-17 19:05

import django.db.models.deletion
import evidence.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cases', '0004_scenereport_scenewitness'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Evidence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('witness_statement', 'Witness statement'), ('forensic', 'Forensic'), ('vehicle', 'Vehicle'), ('identity_document', 'Identity document'), ('other', 'Other')], max_length=32)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('witness_transcription', models.TextField(blank=True, default='')),
                ('coroner_result', models.TextField(blank=True, null=True)),
                ('identity_db_result', models.TextField(blank=True, null=True)),
                ('vehicle_model', models.CharField(blank=True, default='', max_length=255)),
                ('color', models.CharField(blank=True, default='', max_length=64)),
                ('plate_number', models.CharField(blank=True, max_length=64, null=True)),
                ('serial_number', models.CharField(blank=True, max_length=64, null=True)),
                ('owner_full_name', models.CharField(blank=True, default='', max_length=255)),
                ('extra_info', models.JSONField(blank=True, default=dict)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidence_items', to='cases.case')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_evidence', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'permissions': [('fill_forensic_results', 'Can fill forensic results (coroner)')],
            },
        ),
        migrations.CreateModel(
            name='EvidenceAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('image', 'Image'), ('video', 'Video'), ('audio', 'Audio'), ('document', 'Document')], max_length=16)),
                ('file', models.FileField(upload_to=evidence.models.evidence_attachment_upload_to)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('evidence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='evidence.evidence')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_evidence_attachments', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddConstraint(
            model_name='evidence',
            constraint=models.CheckConstraint(condition=models.Q(('plate_number__isnull', False), models.Q(('plate_number', ''), _negated=True), ('serial_number__isnull', False), models.Q(('serial_number', ''), _negated=True), _negated=True), name='vehicle_plate_xor_serial'),
        ),
    ]
