# Generated by Django 5.2.11 on 2026-02-15 23:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='case',
            options={'permissions': [('view_all_cases', 'Can view all cases')]},
        ),
    ]
