# Generated by Django 5.2.11 on 2026-02-16 00:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0002_alter_case_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Complaint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('crime_level', models.CharField(choices=[('critical', 'Critical'), ('level_1', 'Level 1'), ('level_2', 'Level 2'), ('level_3', 'Level 3')], max_length=20)),
                ('current_status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('cadet_rejected', 'Cadet Rejected'), ('cadet_approved', 'Cadet Approved'), ('officer_rejected', 'Officer Rejected'), ('officer_approved', 'Officer Approved'), ('invalid', 'Invalid')], default='submitted', max_length=32)),
                ('invalid_attempts', models.PositiveSmallIntegerField(default=0)),
                ('cadet_message', models.TextField(blank=True, default='')),
                ('officer_message', models.TextField(blank=True, default='')),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cadet_reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('officer_reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('cadet_reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='complaints_cadet_reviewed', to=settings.AUTH_USER_MODEL)),
                ('case', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='complaint', to='cases.case')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='complaints_created', to=settings.AUTH_USER_MODEL)),
                ('officer_reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='complaints_officer_reviewed', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'permissions': [('view_all_complaints', 'Can view all complaints'), ('cadet_review_complaint', 'Can cadet review complaints'), ('officer_review_complaint', 'Can officer review complaints')],
            },
        ),
        migrations.CreateModel(
            name='ComplaintComplainant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=16)),
                ('cadet_reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('cadet_reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='complainant_entries_reviewed', to=settings.AUTH_USER_MODEL)),
                ('complaint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='complainants', to='cases.complaint')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='complainant_entries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('complaint', 'user')},
            },
        ),
    ]
