# Generated by Django 5.2.11 on 2026-02-16 10:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0003_complaint_complaintcomplainant'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SceneReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scene_datetime', models.DateTimeField()),
                ('status', models.CharField(choices=[('pending', 'Pending Approval'), ('approved', 'Approved')], default='pending', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_scene_reports', to=settings.AUTH_USER_MODEL)),
                ('case', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='scene_report', to='cases.case')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_scene_reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'permissions': [('view_all_scene_reports', 'Can view all scene reports'), ('create_scene_report', 'Can create scene reports'), ('approve_scene_report', 'Can approve scene reports'), ('auto_approve_scene_report', 'Can auto-approve scene reports (chief bypass)')],
            },
        ),
        migrations.CreateModel(
            name='SceneWitness',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=32)),
                ('national_id', models.CharField(max_length=32)),
                ('scene_report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='witnesses', to='cases.scenereport')),
            ],
            options={
                'unique_together': {('scene_report', 'phone', 'national_id')},
            },
        ),
    ]
