# Generated by Django 5.x on 2026-02-18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cases", "0004_scenereport_scenewitness"),
        ("investigations", "0004_interrogation"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Trial",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "verdict",
                    models.CharField(
                        blank=True,
                        choices=[("guilty", "Guilty"), ("innocent", "Innocent")],
                        max_length=16,
                        null=True,
                    ),
                ),
                ("punishment_title", models.CharField(blank=True, default="", max_length=255)),
                ("punishment_description", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("verdict_at", models.DateTimeField(blank=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "case",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="trials",
                        to="cases.case",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="trials_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "suspect",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="trials",
                        to="investigations.casesuspect",
                    ),
                ),
                (
                    "verdict_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="trial_verdicts_given",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "permissions": [
                    ("judge_verdict_trial", "Can create/update trial verdict (judge)"),
                    ("view_case_report", "Can view case report"),
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="trial",
            constraint=models.UniqueConstraint(
                fields=("case", "suspect"), name="uniq_trial_case_suspect"
            ),
        ),
    ]

